### ISSUE TITLE
如何更改key.bin啊

### ISSUE THREAD

**Issue by billy74** [Paulkm2006/cloudreve-heroku-pro#1]
这个key.bin应该是授权文件吧，这个有办法自己本地化么？
大佬能否去除授权啊 本地存储只想用用户多策略而已，199的价格有点贵了。
billy74@qq.com 感激不尽

**Comment by Paulkm2006** [comment]
授权不是我的管理范围，如果只想免费推荐普通版（ https://github.com/useblue/Cloudreve-Heroku ）
